### ISSUE TITLE
Multiline test matchers

### ISSUE THREAD

**Issue by kaukas** [janko/vim-test#162]
Hello.

Thank you for the fantastic `vim-test` tool! I'm using it for a while now and it helps me get closer to the TDD nirvana. :-)

Lately I've been using it for Rust development and found out that `TestNearest` does not recognize the current test I'm in. `cargo test` does not give an easy way to run a particular test (you need to distinguish between example, integration, benchmark, etc tests). But it does allow a test function name to be passed in. The trouble is I can't seem to get the regexp to match a test function. An example test:

```rust
#[test]
fn it_works() {
    assert!(1 == 1);
}
```

Here's a pattern that would match the function name: `\v^\s*#\[test\]\n\s*fn (\w+)%(\(\))`. Unfortunately, even though the regexp would match the new line (`\n`) the `test#base#nearest_test` uses `reverse(getbufline(...))` to iterate over lines one by one. Therefore we can't find tests by a multiline regexp.

I know next to nothing about VimScript. Is there a way to (backwards) iterate over matches in a file starting from a given position? Can this be used instead of line-by-line iteration?

Thank you!

**Comment by janko-m** [comment]
@kaukas That is a good question. The reason why test.vim is doing line-to-line iteration is because this way it can detect indentation, which is what's used to detect testing namespaces (which `go test` presumably doesn't have, but JavaScript and Ruby testing frameworks do). If we just read the whole file and do multiline pattern matching, it would be difficult to detect consistent indentation with a regex. But maybe not impossible.

**Comment by kaukas** [comment]
Hello, @janko-m,

I know very little about `cargo test` and nothing about VimL. The [`cargo-nearest-test`](https://github.com/janko-m/vim-test/compare/master...kaukas:cargo-nearest-test?expand=1) branch contains my first attempt at the "nearest test" detection. Do you think it's worth going further? Please keep in mind that:

- The code looks and is complicated. My first contact with VimL.
- The algorithm is inefficient. It creates a string from the current line to the end of the file. Searches the string. Adds the line above. Searches again. And so on. Potentially very slow. I could not come up with a better algorithm.
- Namespaces are ignored (I am not sure how they work with `cargo test`), for now.
- Only simple tests might work. `cargo` also supports benchmark, integration, etc tests. Not sure about those.

If I find some time I could continue coding. Namespaces, intermediate directives, etc. What do you think?

**Comment by codeinabox** [comment]
@kaukas are you still affected by this? I can look into your PR when I get a spare moment

**Comment by kaukas** [comment]
@codeinabox, I don't think the code is mergeable upstream as it is. I kind of scratched my own itch to get the simplest case running (see [`cargo-nearest-test`](https://github.com/janko-m/vim-test/compare/master...kaukas:cargo-nearest-test?expand=1)) but it needs cleanup, documentation, a more thorough and perhaps a more efficient implementation. I am sorry but I don't have time to do this now. If anyone would like to pick up from here I'd be very happy!

**Comment by kaukas** [comment]
@ShahinSorkh, thank you for the great PR! Dropping my code.
