### ISSUE TITLE
Support for Makefile and custom errorformat

### ISSUE THREAD

**Issue by timlag1305** [janko/vim-test#345]
I am using this plugin to run tests on Ada code. This required me to use a Makefile and AUnit (like JUnit) to execute my tests. I have the test cases running using `:TestSuite`. The `errorformat` for the tests needs to be different from the `errorformat` when compiling. Is this possible?

**Comment by janko** [comment]
If you're using the `dispatch` strategy, you can tell vim-dispatch to use a specific Vim compiler for your make command:

```rb
let g:dispatch_compilers = { 'make test': 'your-compiler' }
```

That Vim compiler should then set the correct `errorformat`. A "Vim compiler" is a vim file `compilers/<name>.vim` in runtime path. You can check some existing ones that came with your Vim distribution to get the gist, so you can create your own. Or you can import/use an existing AUnit/JUnit Vim compiler if one exists.

Test.vim itself doesn't deal with Vim compilers or setting `errorformat`, as that's strategy-specific.
