### ISSUE TITLE
PHPUnit tests passing in CLI, but not in vim-test

### ISSUE THREAD

**Issue by jonleopard** [janko/vim-test#352]
Hello!

First off, thanks for making this plugin! There are no bugs that I am reporting here, this is most likely an error on my part.  When I run `vendor/bin/phpunit tests/Feature/ProjectsTest.php` manually from the CLI, my test passes with no errors. But when I run `:TestFile`, it gives this error:

```
1) Tests\Feature\ProjectsTest::a_user_can_create_a_project
Illuminate\Session\TokenMismatchException:
```

Does vim-test look for rules defined in the phpunit.xml file? 

Any tips or suggestions would be great :)

**Comment by janko** [comment]
You can see which command vim-test runs, and then compare how it differs from the command you're running in the shell. On Neovim you can see the command in the buffer "filename", and for Vim the `basic` strategy automatically prints out the test command.

**Comment by jonleopard** [comment]
Thanks @janko :)
