### ISSUE TITLE
Don't clobber mappings

### ISSUE THREAD

**Issue by Tanath** [janko/vim-test#354]
Your recommended mappings in the README clobber existing commands, which should be avoided. For instance `<c-o>` is very useful with `<c-i>` for jumping through recent locations.

**Comment by janko** [comment]
I also use `<c-o>` and `<c-i>` daily, but the suggested mapping in the README only applies to the opened Neovim terminal. Is it that you want to use `<c-o>` on the Terminal window?

There has been some discussion about the possibility of bringing the user to normal mode by default, and then mapping `<Enter>` to exit the terminal. That's how Vim 8 terminal works now.

**Comment by Tanath** [comment]
Sorry, I missed that it was a terminal-only mapping.

> That's how Vim 8 terminal works now.

What? No it doesn't. It behaves as expected (testing vim 8.1).  
Quitting on <kbd>enter</kbd> doesn't make mnemonic sense. If you forgot you were in normal mode you could exit accidentally. I'd be rather annoyed if I lost my terminal and its output due to an accidental <kbd>enter</kbd>. Just use <kbd>ctrl</kbd>+<kbd>d</kbd> in insert mode. If you want a mapping to exit terminal from normal mode I would advise something else.

This issue was my mistake due to misreading. I'll close it now.

**Comment by janko** [comment]
> What? No it doesn't.

Sorry, I meant the `vimterminal` vim-test strategy.
