### ISSUE TITLE
How to pass in Jest config?

### ISSUE THREAD

**Issue by tomspeak** [janko/vim-test#357]
Hey,

I am trying to get this to run a single jest test file, it runs, but it does not pick up my jest configuration.

In my `package.json` i usually run the tests via `jest --config ./config/jest/jest.config.json` -- is it possible to tell `vim-test` where to look for the config file? Without proper set up my tests wont run.

Cheers.

**Comment by janko** [comment]
You should be able to do this by changing the executable:

```vim
let g:test#javascript#jest#executable = 'jest --config ./config/jest/jest.config.json'
```

**Comment by tomspeak** [comment]
Finally, a reason to implement project specific `.vimrc`.

This works brilliantly.

A note to anyone seeing this, you most likely need to add `npx` or `yarnpkg` to the beginning of that command to get it work.

Appreciate your help @janko.
