### ISSUE TITLE
`IOError: [Errno 4] Interrupted system cal`

### ISSUE THREAD

**Issue by Migacz85** [janko/vim-test#358]
Tests are running as expected. I'm really happy about that. Great job ! 
But I run in to issues unfortunately :
Hard for me to spot what is exactly triggering this but when I added this plugin this error showed up. `IOError: [Errno 4] Interrupted system cal` . 
Few times I run in to situation that vim stops working complettly. 
Also what is strange I have mappings:
`cP` for coppying current line to system clipboard and immediatelly when Im adding this plugin its sops working. 

How i Can troubleshoot this?

**Comment by janko** [comment]
I'm not sure what's wrong, test.vim is pretty unobtrusive IMO. Which test.vim strategy and test runner are you using? Are you using Vim or Neovim? If yes, which version?

**Comment by Migacz85** [comment]
Sorry I was wrong, is not a fault of this plugin. :-) I was implementing also `vim-which-key` plugin and this was probably a one to blame for.

**Comment by Migacz85** [comment]
@janko but I'm still experiencing it and don't have any idea how to spot exactly what is causing it. Maybe you have some ideas how I can troubleshoot this? I'm using Vim 8.1 on latest manjaro. I'm using dispatch hidden.  It's super hard form me to spot on what is causing that. But What I'm know is that is rarely happening on read or write to the file.

**Comment by janko** [comment]
Have you tried running the test command via `:Dispatch[!]` directly? This error most likely stems from dispatch.vim, not from test.vim; test.vim just computes the test command and calls the `:Dispatch[!]` command in the end.

If you get the same error, you should open an issue there instead.

**Comment by janko** [comment]
Closing, as this issue is most likely coming from Dispatch.vim and should be discussed there.
