### ISSUE TITLE
TestNearest failed to get file position on the first time with jest

### ISSUE THREAD

**Issue by hulucc** [janko/vim-test#359]
![image](https://user-images.githubusercontent.com/4343900/56038612-f597f480-5d64-11e9-8cf8-8b66f32f77d6.png)

Call again:
![image](https://user-images.githubusercontent.com/4343900/56038665-09dbf180-5d65-11e9-85b4-64f9e952dc18.png)

**Comment by janko** [comment]
Thanks for reporting, that's a strange error. vim-test doesn't really maintain state, except the last position, which shouldn't change the behaviour in the way you described. Could you give me a minimal JavaScript project which reproduces the issue?

**Comment by ngfgrant** [comment]
hey @hulucc 

I tried to reproduce your error but can't seem to. 

A couple of basic tests

<img width="603" alt="Screenshot 2019-10-15 at 21 32 31" src="https://user-images.githubusercontent.com/6362273/66867592-85785e80-ef93-11e9-861c-5b0614df9ae8.png">

When I `TestNearest`:

<img width="776" alt="Screenshot 2019-10-15 at 21 32 40" src="https://user-images.githubusercontent.com/6362273/66867634-9b861f00-ef93-11e9-9405-7f9bb8777e47.png">

Even if I add a confusing test like `bye1` which is close to match `bye` it still correctly matches

<img width="824" alt="Screenshot 2019-10-15 at 21 35 45" src="https://user-images.githubusercontent.com/6362273/66867766-e4d66e80-ef93-11e9-8a5f-e3976a1ac73e.png">

This is a totally minimal project with just those tests.

**Comment by hulucc** [comment]
So i guess its something wrong with my vim or windows. Close it for now.

**Comment by hulucc** [comment]
It turn out is a something wrong about AsyncRun.
