### ISSUE TITLE
maven/gradle file_pattern regex anchored to start of filepath

### ISSUE THREAD

**Issue by willjp** [janko/vim-test#363]
Running `:TestNearest` within a valid maven test file was echoing 'Not a test file'.

The issue appears to be that the default maven/gradle `g:test#java#..#file_pattern` is anchored to the start of the match.

``` vim
" autoload/java/maventest.vim

if !exists('g:test#java#maventest#file_pattern')
  let g:test#java#maventest#file_pattern = '\v^([Tt]est.*|.*[Tt]est(s|Case)?)\.java$'
endif
```

but the match is being performed on the full filepath

``` vim
" autoload/test.vim

function! test#run(type, arguments) abort
  " ...
  if test#test_file(expand('%'))
  " ...
```

It's an easy configuration fix, but I though you might want to know :)

**Comment by janko** [comment]
This has been fixed in https://github.com/janko/vim-test/pull/364, thanks!
