### ISSUE TITLE
Does not work - could not find package.json file

### ISSUE THREAD

**Issue by alex-shamshurin** [janko/vim-test#372]
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/1595209/59562912-81671f00-903b-11e9-949c-403486e42463.png">

`package.json` is in the root.

**Comment by alex-shamshurin** [comment]
test runner is 'Jest'

**Comment by JoosepAlviste** [comment]
I have a similar case where my project is split into an `api/` and an `app/`. Something like this:

```
/my-project/
-- api/
-- -- package.json
-- app/
-- -- src/components/
-- -- -- Foo.js
-- -- -- Foo.test.js
-- -- package.json
-- package.json  < includes general dependencies like husky and utility scripts
```

This means that this plugin always wants to use the `/my-project/package.json` file and not the `package.json` closest to the file I'm editing. It seems logical to me that the `package.json` would be searched for recursively from the file I'm editing. This way it should always be correct.

I *think* this is how most plugins that want to use `node_modules/` work but I'm not 100% sure on that. It is definitely how I would expect it to work though. Any ideas?

I would be open to trying to implement this if it seems OK with you, @janko.

**Comment by janko** [comment]
I believe this is already being discussed in https://github.com/janko/vim-test/issues/272.

**Comment by janko** [comment]
Closing in favour of https://github.com/janko/vim-test/issues/272
