### ISSUE TITLE
Specify python executable for unit tests

### ISSUE THREAD

**Issue by xulongwu4** [janko/vim-test#373]
Is there a way to specify the executable to be used with unit tests? For example, in my setup I would like to use `python3` as the executable for unit tests instead of `python`. Is there a easy way to do that?

**Comment by janko** [comment]
https://github.com/janko/vim-test/blob/master/README.md#executable

**Comment by fdelacruz** [comment]
Hi , would this be the setting?
let g:test#python#unittest#executable = 'python3'

Cheer

**Comment by fdelacruz** [comment]
So, since we're using pyunit for unittest the setting is
let g:test#python#**pyunit**#executable = 'python3 -m unittest'
