### ISSUE TITLE
Specifying global and granular options for a test runner

### ISSUE THREAD

**Issue by dbatten5** [janko/vim-test#375]
Suppose I want all phpunit tests run with the `--bootstrap vendor/autoload.php` cli option and I want all `suite` tests to run with the `--stop-on-failure` option, how would this be achieved? I can add the `--bootstrap` command to each individual strategy but this feels like overkill. Is something like the following already possible and if not would it be beneficial?
```
let test#php#phpunit#options = {
  \ 'all':   '--bootstrap vendor/autoload.php',
  \ 'suite': '--stop-on-failure',
\}
```

**Comment by janko** [comment]
It doesn’t exist yet, but I’d welcome a PR for that 👍

**Comment by dbatten5** [comment]
done 👍

**Comment by janko** [comment]
Added in https://github.com/janko/vim-test/pull/376
