### ISSUE TITLE
TestVisit does not accept cli arguments

### ISSUE THREAD

**Issue by geoffharcourt** [janko/vim-test#380]
Hi!

TestVisit is super-useful. I was hoping to pass it an RSpec command line argument, but noticed that it's the only one of the Test* commands that doesn't take the arguments splat. Is there a reason for this? I'm happy to make a PR if there's not intent behind the current behavior.

**Comment by janko** [comment]
`:TestVisit` simply brings your vim buffer to the last ran test, it doesn't run any test commands. So it wouldn't make sense for it to accept command line arguments, because they wouldn't be used for anything.

**Comment by geoffharcourt** [comment]
I misunderstood its purpose! Thanks for the clarification.
