### ISSUE TITLE
It doesn't work with minitest

### ISSUE THREAD

**Issue by phuongnd08** [janko/vim-test#383]
I'm working on this https://github.com/remitano/ruby-await-node (commit e11d61c) which use minitest

Trying to run the test file with `t Ctrl+f` but it's saying "Not a test file".

**Comment by phuongnd08** [comment]
Switch over to rspec and vim-test works fine.

**Comment by janko** [comment]
The problem in your previous Minitest version is that vim-test's runner expects test file to be called `*_test.rb`, and yours was called `test/test_ruby_await_node.rb`. I think the `test_*.rb` naming convention is common enough that vim-test should support it.

**Comment by uzxmx** [comment]
@phuongnd08  One quick solution is to add below snippet to your ~/.vimrc

```
let g:test#ruby#minitest#file_pattern = '\v(((^|/)test_.+)|_test)\.rb$'
```

But if you run a suit or from a directory, it won't work. So I made this PR #450 to solve it properly.
