### ISSUE TITLE
Mocha tests result in "Not a test file"

### ISSUE THREAD

**Issue by akrejczinger** [janko/vim-test#393]
Probably a duplicate of #233 but I cannot reopen tickets.

Whenever I try to run mocha tests, vim-test always shows "Not a test file".
I tried everything to make the tests match. I changed the regex like this:
```vim
let g:test#javascript#runner = "mocha"
let g:test#javascript#mocha#file_pattern = '.*'
```

Running `echo expand('%') =~ '.*'` while in the test file returns 1, and yet vim-test does not want to recognize the file as a test file.
The test files are called `<name>.spec.js` and they are in nested directories under a `tests` directory, so even with the default regex they should work (and the echo command returns 1 as well).
I tried disabling all my other plugins / settings in the .vimrc but it didn't help.
What could be the issue here?

**Comment by janko** [comment]
This is the function that checks whether something is a test file: https://github.com/janko/vim-test/blob/1b82c6929e9d87ca756569c1640320d027498364/autoload/test/javascript/mocha.vim#L5-L8

So, if the file pattern check is passing, my only guess is that the `test#javascript#has_package` call is for some reason returning false for your project: https://github.com/janko/vim-test/blob/1b82c6929e9d87ca756569c1640320d027498364/autoload/test/javascript.vim#L6-L14

On obvious case is if Mocha is loaded in your project via dependency, and is not directly present in your `package.json`.

**Comment by akrejczinger** [comment]
You are right, the issue was that Mocha was not in the `package.json` file.
