### ISSUE TITLE
Support running containerized tests (Docker)

### ISSUE THREAD

**Issue by jackno** [janko/vim-test#442]
Add support for running tests through Docker containers.

Example:
`docker-compose run app python manage.py test`

**Comment by jackno** [comment]
This could literally be as easy as prepending `docker-compose run <service-name>` to all commands. Looking into it.

**Comment by janko** [comment]
You can override the executable for each runner, in your case via `let g:test#python#pyunit#executable ‘command’` (or whatever is the name of the runner).

**Comment by jackno** [comment]
This is a nice simple workaround for now, thanks.

It also exposes a new issue that I'm opening in a different thread.

**Comment by codeinabox** [comment]
Another option is using strategies or transformations which are discussed in these tickets #53  #254
