### ISSUE TITLE
Readme inconsistent with Python 'unittest' and runner 'pyunit'

### ISSUE THREAD

**Issue by jackno** [janko/vim-test#453]
Failures occurring when setting `test#python#runner = 'unittest'`

README states:
```shell
let test#python#runner = 'pytest'
" Runners available are 'pytest', 'nose', 'nose2', 'djangotest', 'djangonose', 'mamba', and Python's built-in 'unittest'
```
The implementation for Python's `unittest` [was named 'pyunit'](https://github.com/janko/vim-test/commit/54ebd839cea9c72a7d217b44201314f6a2abd859). Either README needs to change to reflect using the 'pyunit' setting rather than 'unittest'. Or in my opinion, the name of the runner should be renamed to 'unittest'.

**Comment by jackno** [comment]
I also forgot to consider compatibility issues for older vimrcs, maybe it would be better to just update the README and leave the runner name as 'pyunit'

**Comment by janko** [comment]
Yeah, I would also like for the runner to be named correctly (what is "pytest" then?), but would prefer to keep backwards compatibility for now. Could you send a PR for the README for now?
