### ISSUE TITLE
Usage with asdf for elixir

### ISSUE THREAD

**Issue by alappe** [janko/vim-test#459]
I've been using vim-test with elixir for a while and love it. Switching to `asdf` for different versions of elixir/erlang in different projects, I do run into trouble though. Most probably a configuration issue on my side, but since I can't figure it out, maybe somebody here has a clue for me.

`:!elixir -v` returns my systems default version of elixir, `v1.10.2`.
`:terminal`, then `elixir -v` in it returns the version my shell uses in my current project using asdf, `v1.9.4`.

Using vim-test, the tests in this project are executed in `v1.10.2` not as expected in `v1.9.4`, requiring recompilation of the project. What can I set to execute it in something like my login shell's environment?

NVIM `v0.4.3`, vim-test `v2.1.0-304-g8300ee6`. No configuration of vim-test except remapping of keys to run it.

Happy to provide any missing info…

**Comment by codeinabox** [comment]
Hello there, I am assuming your tests are written in `exunit` is that correct? The command that the runner uses is just `elixir` so I would compare the path of your shell with that used by the strategy and vim, it's possible the latter is not picking up the path changes from `asdf`.

**Comment by alappe** [comment]
Indeed they're written in `exunit`. I assumed the default strategy for neovim is `:terminal`, which should work according to the output above, but instead it looks like it's `:!`, which is confirmed above as non-working. Switching to `let test#strategy = "neovim"` has the same issue, except for the fact that it opens in a split window.

**Comment by codeinabox** [comment]
Are you running `asdf` from within `:terminal`?

**Comment by alappe** [comment]
`asdf` is triggered from my shell config, so spawning a new shell does run it, yes. And if I run it by hand, as shown in the original post, the output is correct and working. So it seems to me that e.g. `:TestNearest` does not really run it in `:terminal`, but I don't know where/how/why…

**Comment by codeinabox** [comment]
Are you using bash? This might help https://vi.stackexchange.com/questions/16019/neovim-terminal-not-reading-bash-profile

**Comment by alappe** [comment]
Using zsh but I assume it could be the same thing. But using `:terminal`, then executing by hand *does work*, using `:TestNearest` etc. does not.

**Comment by alappe** [comment]
Hm, didn't get any further. According to `:h !` and `:h terminal`, but should use `shell` as configured, in my case a zsh. I don't see any difference between the two ways to execute, but maybe it's not a `vim-test` thing at all. I will try to talk to some neovim people about it and report back if I find a solution.

**Comment by alappe** [comment]
So, trying out the different commands, the difference seems to be if the shell is interactive or not. Asdf, sourced from `~/.zshrc` is only sourced for an interactive shell because zsh only reads this file in this case.

**Comment by alappe** [comment]
I solved it by moving the asdf script to `.zshenv` which gets sourced also for non-interactive shells – works perfectly with `vim-test` now. Thanks @codeinabox for sparring…
